In [1]:
import numpy as np

# TASK1
#### Створіть одновимірний масив із 10 випадкових чисел від 0 до 100.
#### Збережіть масив у змінну і виведіть його на екран.
#### Знайдіть мінімальне, максимальне та середнє значення масиву за допомогою вбудованих функцій NumPy.
#### Відсортуйте масив за зростанням і виведіть результат.
#### Відобразіть масив до і після сортування.

In [2]:
arr1 = np.random.randint(0, 100, size=10)
print(arr1)

[ 7 76 79 62 68 60 60  2 75 26]


In [3]:
print(f'Min: {arr1.min()}, Max: {arr1.max()}, Average: {arr1.mean()}')

Min: 2, Max: 79, Average: 51.5


In [4]:
sorted_arr1 = np.sort(arr1)
print(f'Before: {arr1} \nAfter: {sorted_arr1}')

Before: [ 7 76 79 62 68 60 60  2 75 26] 
After: [ 2  7 26 60 60 62 68 75 76 79]


# TASK2
#### Створіть двовимірний масив розміром 4×4, заповнений випадковими цілими числами від 1 до 50.
#### Виведіть масив у читабельному вигляді (у вигляді таблиці).
#### Знайдіть суму елементів за кожним рядком і за кожним стовпчиком (використовуйте параметр axis).
#### Визначте загальне середнє значення масиву.
#### Виведіть усі результати в зручному вигляді
#### (наприклад: "Суми за рядками: ...","Суми за стовпцями: ...").

In [8]:
arr2 = np.random.randint(1, 50, size=(4, 4))
print(arr2)

[[33  5 29 32]
 [26  5 49  3]
 [44  7 16  8]
 [23 39 25 30]]


In [15]:
for i in range(0, 4):
    for j in range(0, 4):
        print(f'|{arr2[i][j]:3}|', end = " ")
    print()

| 33| |  5| | 29| | 32| 
| 26| |  5| | 49| |  3| 
| 44| |  7| | 16| |  8| 
| 23| | 39| | 25| | 30| 


In [16]:
print(f'Sum in row: {arr2.sum(axis=1)}, in columns: {arr2.sum(axis=0)} \nAverage in row: {arr2.mean(axis=1)}, in column: {arr2.mean(axis=0)}')

Sum in row: [ 99  83  75 117], in columns: [126  56 119  73] 
Average in row: [24.75 20.75 18.75 29.25], in column: [31.5  14.   29.75 18.25]


# TASK3
#### Створіть масив розміром 3×5, заповнений числами від 0 до 14.
#### Виведіть вихідний масив.
#### Виконайте транспонування масиву (рядки стають стовпцями, а стовпці — рядками).
#### Застосуйте операцію reshape, щоб отримати масив 5×3.
#### Відобразіть результати на екран.

In [21]:
arr3 = np.arange(0, 15).reshape(3, 5)
print(arr3)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [23]:
print(arr3.reshape(5, 3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


# TASK4
#### Створіть масив розміром 10×10, заповнений випадковими числами з плаваючою крапкою від 0 до 1.
#### Знайдіть мінімальне та максимальне значення в усьому масиві.
#### Визначте індекси мінімального та максимального елементів
#### (наприклад: (рядок, стовпець)).
#### Виведіть сам масив і окремо знайдені значення разом з їхніми індексами.

In [24]:
arr4 = np.random.rand(10, 10)

In [27]:
print(arr4)
mn = arr4.min()
mx = arr4.max()

for i in range(0, 10):
    for j in range(0, 10):
        if arr4[i][j] == mn:
            mn_idx = (i, j)
        if arr4[i][j] == mx:
            mx_idx = (i, j)
print(f'Min idx: {mn_idx}, Max idx: {mx_idx}')

[[0.33236358 0.72260449 0.33022633 0.14822124 0.12622864 0.10243236
  0.80429531 0.6087128  0.58384258 0.86222241]
 [0.06802958 0.54550983 0.67539392 0.80088299 0.19679831 0.52723437
  0.15885383 0.74907383 0.49805853 0.61891205]
 [0.0487623  0.65278068 0.97058624 0.88243979 0.31479565 0.85315554
  0.68578127 0.57327757 0.69318579 0.29809762]
 [0.30668272 0.87533832 0.76299033 0.90408237 0.22174098 0.72784598
  0.47725952 0.52973488 0.10091286 0.38595599]
 [0.54591061 0.6243183  0.82630777 0.37798009 0.05889356 0.9994081
  0.1094257  0.76148713 0.26787563 0.22123053]
 [0.52052083 0.53048742 0.41391716 0.91905687 0.32290685 0.84469727
  0.12320377 0.72059109 0.40811737 0.11278979]
 [0.39755155 0.9192782  0.68233335 0.32515573 0.22952321 0.49651108
  0.39404339 0.72734688 0.39931703 0.19258301]
 [0.56075002 0.91730482 0.86267311 0.50360681 0.47347687 0.29965602
  0.69135964 0.36855851 0.03225126 0.60376668]
 [0.4774874  0.39367697 0.29830485 0.21354807 0.5473627  0.65094332
  0.38793224 

# TASK5
#### Створіть одновимірний масив із 15 випадкових цілих чисел від -10 до 10.
#### Виведіть масив.
#### За допомогою булевої індексації виберіть тільки додатні елементи.
#### За допомогою булевої індексації виберіть тільки парні елементи.
#### Виведіть обидва результати на екран.

In [28]:
arr5 = np.random.randint(-10, 11, size=15)
print(arr5)
print(arr5[arr5 > 0])
print(arr5[arr5 % 2 == 0])

[ -2  -4   5   2 -10   2   0   4   0  -1   9  -3  -1   2   4]
[5 2 2 4 9 2 4]
[ -2  -4   2 -10   2   0   4   0   2   4]


# TASK6
#### Створіть два одновимірні масиви довжиною 5: перший заповніть числами від 1 до 5, другий — числами від 6 до 10.
#### Об'єднайте їх в один масив за допомогою np.concatenate.
#### Побудуйте двовимірний масив 2×5, у якому перший рядок — перший масив, а другий рядок — другий масив.
#### Об'єднайте обидва масиви в одну колонку (розмірність 5×2).
#### Виведіть усі три результати на екран.

In [29]:
arr6_1 = np.arange(1, 6)
arr6_2 = np.arange(6, 11)
print(f'{arr6_1}\n{arr6_2}')

[1 2 3 4 5]
[ 6  7  8  9 10]


In [30]:
arr6_3 = np.concatenate((arr6_1, arr6_2))
print(arr6_3)

[ 1  2  3  4  5  6  7  8  9 10]


In [32]:
arr6_4 = arr6_3.reshape(2, 5)
print(arr6_4)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [41]:
for i in range(5):
    pair = int(arr6_3[i]), int(arr6_3[i + 5])
    print(pair)

(1, 6)
(2, 7)
(3, 8)
(4, 9)
(5, 10)
