In [2]:
import numpy as np

# Task1

#### Створіть масив із 20 цілих чисел у діапазоні від 0 до 50.
#### Виведіть вихідний масив.
#### Запитайте у користувача число (порогове значення).
#### Визначте кількість елементів масиву, що перевищують введене користувачем значення, і виведіть результат.
#### Знайдіть максимальне значення в масиві та позицію його першої появи, виведіть обидва результати.
#### Відсортуйте масив за спаданням і виведіть відсортований масив.

In [3]:
arr1 = np.random.randint(0, 51, size=20)
print(arr1)

[44 42 14 14 37 40 24 43  6  0 38 12 10 13 46 15 40 28 36 39]


In [5]:
n = int(input("Enter n: "))
print(len(arr1[arr1 > n]))

Enter n:  20


12


In [7]:
print(f'Min: {arr1.min()}, idx: [{np.argmin(arr1)}]')
print(f'Max: {arr1.max()}, idx: [{np.argmax(arr1)}]')

Min: 0, idx: [9]
Max: 46, idx: [14]


In [10]:
print(np.sort(arr1)[::-1])

[46 44 43 42 40 40 39 38 37 36 28 24 15 14 14 13 12 10  6  0]


# Task2

#### Запитайте в користувача верхню та нижню межу діапазону чисел.
#### Створіть квадратну матрицю 5×5 з цілими значеннями в цьому діапазоні.
#### Виведіть вихідну матрицю.
#### Отримайте головну діагональ і виведіть діагональні елементи.
#### Підрахуйте суму елементів головної діагоналі та виведіть результат.
#### Обнуліть елементи строго вище головної діагоналі та виведіть змінену матрицю.

In [11]:
n1 = int(input("Enter lowest value: "))
n2 = int(input("Enter highest value: "))
arr2 = np.random.randint(n1, n2 + 1, size=(5, 5))
print(arr2)

Enter lowest value:  1
Enter highest value:  9


[[6 1 6 9 1]
 [5 4 9 2 5]
 [8 6 5 5 5]
 [5 1 2 6 2]
 [3 4 4 8 2]]


In [18]:
diag = []
for i in range(5):
    diag.append(int(arr2[i][i]))
print(diag)

[6, 4, 5, 6, 2]


In [19]:
sum = 0
for v in diag:
    sum += v
print(f'Diagonal sum: {sum}')

Diagonal sum: 23


In [20]:
for i in range(5):
    for j in range(5):
        if j > i:
            arr2[i][j] = 0
print(arr2)

[[6 0 0 0 0]
 [5 4 0 0 0]
 [8 6 5 0 0]
 [5 1 2 6 0]
 [3 4 4 8 2]]


# Task3

#### Запитайте у користувача початок і кінець діапазону чисел.
#### Сформуйте послідовність цілих чисел у вказаному діапазоні.
#### Перетворіть послідовність на матрицю розміром 6×5 і виведіть її.
#### Підрахуйте суму елементів у кожному рядку і виведіть отриманий одновимірний масив сум.
#### Визначте максимальні значення за кожним стовпчиком і виведіть отриманий одновимірний масив максимумів.

In [21]:
s = int(input("Enter start: "))
e = int(input("Enter end: "))
arr3 = np.arange(s, e+1)

Enter start:  1
Enter end:  25


In [22]:
print(arr3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [25]:
if len(arr3) < 30:
    zeros = np.zeros(30 - len(arr3))
    arr3_2 = np.concatenate((arr3, zeros))
elif len(arr3) > 30:
    arr3_2 = arr3[:30]
else:
    arr3_2 = arr3

matrix = arr3_2.reshape(6, 5)
print(matrix)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]
 [ 0.  0.  0.  0.  0.]]


In [26]:
print(f'Sum in rows: {matrix.sum(axis=1)}')
print(f'Max in columns: {matrix.max(axis=0)}')

Sum in rows: [ 15.  40.  65.  90. 115.   0.]
Max in columns: [21. 22. 23. 24. 25.]


# Task4

#### Запитайте в користувача діапазон значень (нижню і верхню межу), включно з від'ємними числами.
#### Створіть одновимірний масив із 15 випадкових цілих чисел у вказаному діапазоні.
#### Виведіть вихідний масив.
#### Виділіть усі від'ємні елементи та виведіть їх як окремий масив.
#### Створіть змінену копію масиву, в якій від'ємні елементи замінено на нулі, і виведіть її.
#### Підрахуйте кількість нульових елементів у зміненому масиві та виведіть результат.

In [28]:
s = int(input("Enter start: "))
e = int(input("Enter end: "))
arr4 = np.random.randint(s, e+1, size=15)
print(arr4)

Enter start:  -15
Enter end:  30


[ -5   4  26  10   2  -3 -12  17  -6  28  25   3  23  -6  22]


In [29]:
arr4_2 = arr4[arr4 < 0]
print(arr4_2)

[ -5  -3 -12  -6  -6]


In [32]:
arr4[arr4 < 0] = 0
print(arr4)

[ 0  4 26 10  2  0  0 17  0 28 25  3 23  0 22]


In [36]:
count = np.sum(arr4 == 0)
print(count)

5


# Task5

#### Запитайте в користувача довжину масивів.
#### Створіть два одновимірні масиви вказаної довжини:
#### перший заповніть випадковими числами від 0 до 10;
#### другий заповніть випадковими числами від 10 до 20.
#### Виведіть обидва вихідні масиви.
#### Об'єднайте масиви в один і виведіть результат.
#### Виконайте поелементне додавання та поелементну різницю вихідних масивів і виведіть обидва результати.

In [3]:
n = int(input("Enter n: "))
arr5_1 = np.random.randint(0, 11, size=n)
arr5_2 = np.random.randint(11, 21, size=n)
print(f"Arr1: {arr5_1} \nArr2: {arr5_2}")

Enter n:  10


Arr1: [ 3  1  3  2  5  0  9  8  4 10] 
Arr2: [11 13 14 18 14 17 15 11 12 20]


In [5]:
arr5_3 = np.concatenate((arr5_1, arr5_2))
print(f'Merged arr: {arr5_3}')

Merged arr: [ 3  1  3  2  5  0  9  8  4 10 11 13 14 18 14 17 15 11 12 20]


In [6]:
print(f"Element sum: {arr5_1 + arr5_2}")
print(f"Element subtraction: {arr5_1 - arr5_2}")

Element sum: [14 14 17 20 19 17 24 19 16 30]
Element subtraction: [ -8 -12 -11 -16  -9 -17  -6  -3  -8 -10]


# Task6

#### Запитайте у користувача розмірність вихідної матриці (наприклад, 4×6).
#### Створіть матрицю з послідовно зростаючих цілих чисел заданої розмірності.
#### Виведіть вихідну матрицю.
#### Запитайте в користувача нові розміри (наприклад, 2×12) і перетворіть матрицю в зазначену форму.
#### Виведіть отриману матрицю.
#### Визначте мінімальні та максимальні значення в кожному рядку нової матриці та виведіть обидва одновимірні масиви.
#### Підрахуйте загальну суму всіх елементів нової матриці та виведіть результат.

In [9]:
r = int(input("Enter rows: "))
c = int(input("Input cols: "))
arr6 = np.arange(1, r*c+1).reshape(r, c)
print(arr6)

Enter rows:  4
Input cols:  6


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]


In [11]:
nr = int(input("Enter new rows: "))
nc = int(input("Input new cols: "))
new_arr6 = arr6.reshape(nr, nc)
print(new_arr6)

Enter new rows:  2
Input new cols:  12


[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]


In [12]:
print(f"Mins: {new_arr6.min(axis=1)}")
print(f"Maxs: {new_arr6.max(axis=1)}")

Mins: [ 1 13]
Maxs: [12 24]


In [13]:
print(f"Sum: {new_arr6.sum()}")

Sum: 300
